version: '2.1'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "task:1:1"
    depends_on:
      - zookeeper
    command: [start-kafka.sh]

  mysqldb:
   image: mysql:5.7
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=root
   healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  
  tms:
        build:
            context: ./
            dockerfile: Dockerfile
        image: tms
        ports:
            - "9000:9000"
        depends_on:
           mysqldb:
               condition: service_healthy
        links:
           - mysqldb
           - kafka
        restart: on-failure
