server:
    port: 9000
spring:
    kafka:
        consumer:
            bootstrap-servers: kafka:9092
            group-id: group_id
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: com.omnius.tms.config.TaskDeserializer
        producer:
            bootstrap-servers: kafka:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: com.omnius.tms.config.TaskSerializer
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
        properties:
          hibernate.jdbc.batch_size: 20
          hibernate.cache.use_query_cache: false
          hibernate.cache.use_second_level_cache: false
          hibernate.cache.use_structured_entries: false
          hibernate.cache.use_minimal_puts: false
          hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysqldb:3306/task?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: root
